controllers/admin_controller.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from models import *
from datetime import datetime

admin = Blueprint('admin', __name__)

@admin.route('/admin', methods=['GET'])
@admin.route('/admin/dashboard', methods=['GET'])
def admin_dashboard():
    if not session.get('admin_logged_in'):
        return redirect(url_for('user.login'))
    
    all_subject = Subject.query.all()
    return render_template("admin_dashboard.html",all_subject=all_subject)
    
@admin.route('/admin/add_subject', methods=['GET','POST'])
def add_subject():
    if not session.get('admin_logged_in'):
        return redirect(url_for('user.login'))
    
    if request.method =='POST':
        subject_name = request.form['subject_name']
        description = request.form['description']

        exist_subject = Subject.query.filter_by(subject_name=subject_name).first()

        if exist_subject:
            flash('⚠ Subject already exist!', 'warning')
            return redirect(url_for('admin.admin_dashboard'))

        if not exist_subject:
            new_subject = Subject(subject_name=subject_name, description=description)

            db.session.add(new_subject)
            db.session.commit()

            flash('✔ Subject added successfully!', 'success')
            return redirect(url_for('admin.admin_dashboard'))
    return redirect(url_for('user.logout'))

@admin.route('/admin/edit_subject/<subject_id>', methods=['GET','POST'])
def edit_subject(subject_id):
    if not session.get('admin_logged_in'):
        return redirect(url_for('user.login'))
    
    if request.method =='POST':
        subject = Subject.query.get_or_404(subject_id)
        subject_name = request.form['subject_name']
        description = request.form['description']

        existing_subject = Subject.query.filter_by(subject_name=subject_name).filter(Subject.id != subject_id).first()

        if existing_subject:
            flash('⚠ Subject already exist!', 'warning')
            return redirect(url_for('admin.admin_dashboard'))

        subject.subject_name = subject_name
        subject.description = description

        db.session.commit()

        flash('✔ Subject edited successfully!', 'success')
        return redirect(url_for('admin.admin_dashboard'))
    return redirect(url_for('user.logout'))

@admin.route('/admin/delete_subject/<subject_id>', methods=['GET','POST'])
def delete_subject(subject_id):
    if not session.get('admin_logged_in'):
        return redirect(url_for('user.login'))
    
    if request.method =='POST':
        subject = Subject.query.get_or_404(subject_id)

        chapters = Chapter.query.filter_by(subject_id=subject_id).all()

        for chapter in chapters:
            quizzes = Quiz.query.filter_by(chapter_id=chapter.id).all()

            for quiz in quizzes:
                Score.query.filter_by(quiz_id=quiz.id).delete()
                Question.query.filter_by(quiz_id=quiz.id).delete()
                db.session.delete(quiz)

            db.session.delete(chapter)

        db.session.delete(subject)
        db.session.commit()

        flash('✔ Subject deleted successfully!', 'success')
        return redirect(url_for('admin.admin_dashboard'))
    return redirect(url_for('user.logout'))
        
@admin.route('/admin/add_chapter/<subject_id>', methods=['GET','POST'])
def add_chapter(subject_id):
    if not session.get('admin_logged_in'):
        return redirect(url_for('user.login'))
    
    if request.method =='POST':
        chapter_name = request.form['chapter_name']
        description = request.form['description']

        existing_chapter = Chapter.query.filter_by(chapter_name=chapter_name,subject_id=subject_id).first()

        if existing_chapter:
            flash('⚠ Chapter already exist!', 'warning')
            return redirect(url_for('admin.admin_dashboard'))
        
        if not existing_chapter:
            new_chapter = Chapter(chapter_name=chapter_name,description=description,subject_id=subject_id)

            db.session.add(new_chapter)
            db.session.commit()

            flash('✔ Chapter added successfully!', 'success')
            return redirect(url_for('admin.admin_dashboard'))
    return redirect(url_for('user.logout'))

@admin.route('/admin/edit_chapter/<int:chapter_id>', methods=['GET','POST'])
def edit_chapter(chapter_id):
    if not session.get('admin_logged_in'):
        return redirect(url_for('user.login'))
    
    if request.method =='POST':
        chapter = Chapter.query.get_or_404(chapter_id)
        chapter_name = request.form['chapter_name']
        description = request.form['description']
        subject_id = chapter.subject_id

        exist_chapter = Chapter.query.filter_by(chapter_name=chapter_name, subject_id=subject_id).filter(Chapter.id != chapter_id).first()

        if exist_chapter:
            flash('⚠ Chapter with this name already exists!', 'warning')
            return redirect(url_for('admin.admin_dashboard'))
        
        chapter.chapter_name = chapter_name
        chapter.description = description
        
        db.session.commit()

        flash('✔ Chapter edited successfully!', 'success')
        return redirect(url_for('admin.admin_dashboard'))
    return redirect(url_for('user.logout'))
   
@admin.route('/admin/delete_chapter/<int:chapter_id>', methods=['GET','POST'])
def delete_chapter(chapter_id):
    if not session.get('admin_logged_in'):
        return redirect(url_for('user.login'))
    
    if request.method =='POST':    
        chapter = Chapter.query.get_or_404(chapter_id)

        quizzes = Quiz.query.filter_by(chapter_id=chapter_id).all()

        for quiz in quizzes:
            Score.query.filter_by(quiz_id=quiz.id).delete()
            Question.query.filter_by(quiz_id=quiz.id).delete()
            db.session.delete(quiz)

        db.session.delete(chapter)
        db.session.commit()

        flash('✔ Chapter deleted successfully!', 'success')
        return redirect(url_for('admin.admin_dashboard'))
    return redirect(url_for('user.logout'))

@admin.route('/admin/chapter/<int:chapter_id>/quizzes', methods=['GET'])
def chapter_quizzes(chapter_id):
    if not session.get('admin_logged_in'):
        return redirect(url_for('user.login'))
    
    chapter = Chapter.query.get_or_404(chapter_id)
    quizzes = chapter.quiz
        
    return render_template('chapter_quizzes.html', chapter=chapter, quizzes=quizzes)

@admin.route("/admin/quizzes", methods=['GET'])
def quiz_management():
    if not session.get('admin_logged_in'):
        return redirect(url_for('user.login'))
    
    all_quizzes = Quiz.query.all()
    all_chapters = Chapter.query.all()

    return render_template('quiz_management.html', all_quizzes=all_quizzes, all_chapters=all_chapters)

@admin.route("/admin/create_quiz", methods=['GET','POST'])
def create_quiz():
    if not session.get('admin_logged_in'):
        return redirect(url_for('user.login'))
    
    if request.method == 'POST':
        chapter_id = request.form['chapter_id']
        quiz_date = request.form['date_of_quiz']

        hours = int(request.form['hours'])
        minutes = int(request.form['minutes'])
        total_minutes = (hours * 60) + minutes

        if len(quiz_date) > 10:
            flash("Invalid Date!", "danger")
            return redirect(url_for('user.register'))

        existing_quizzes = Quiz.query.filter_by(chapter_id=chapter_id).all()
        
        quiz_number = len(existing_quizzes) + 1
        quiz_remark = f"Quiz {quiz_number}"
        
        new_quiz = Quiz(chapter_id=chapter_id, date_of_quiz=quiz_date, duration=total_minutes, remarks=quiz_remark)

        db.session.add(new_quiz)
        db.session.commit()

        flash('✔ Quiz added successfully!', 'success')
        return redirect(url_for('admin.quiz_management'))
    return redirect(url_for('user.logout'))

@admin.route('/admin/edit_quiz/<quiz_id>', methods=['GET','POST'])
def edit_quiz(quiz_id):
    if not session.get('admin_logged_in'):
        return redirect(url_for('user.login'))
    
    quiz = Quiz.query.get_or_404(quiz_id)

    if request.method == 'POST':
        quiz_date = request.form['date_of_quiz']
        
        hours = int(request.form['hours'])
        minutes = int(request.form['minutes'])
        total_minutes = (hours * 60) + minutes

        if len(quiz_date) > 10:
            flash("Invalid Date!", "danger")
            return redirect(url_for('admin.edit_quiz', quiz_id=quiz_id))

        quiz.date_of_quiz = quiz_date
        quiz.duration = total_minutes

        db.session.commit()

        flash('✔ Quiz edited successfully!', 'success')
        return redirect(url_for('admin.quiz_management'))

    return redirect(url_for('user.logout'))

@admin.route('/admin/delete_quiz/<quiz_id>', methods=['GET','POST'])
def delete_quiz(quiz_id):
    if not session.get('admin_logged_in'):
        return redirect(url_for('user.login'))
    
    if request.method =='POST':
        quiz = Quiz.query.get_or_404(quiz_id)

        Question.query.filter_by(quiz_id=quiz_id).delete()
        Score.query.filter_by(quiz_id=quiz_id).delete()

        db.session.delete(quiz)
        db.session.commit()

        flash('✔ Quiz deleted successfully!', 'success')
        return redirect(url_for('admin.quiz_management'))
    return redirect(url_for('user.logout'))

@admin.route("/admin/add_question/<int:quiz_id>", methods=['GET','POST'])
def add_question(quiz_id):
    if not session.get('admin_logged_in'):
        return redirect(url_for('user.login'))
    
    if request.method =='POST':    
        statement = request.form['statement']
        option1 = request.form['option1']
        option2 = request.form['option2']
        option3 = request.form['option3']
        option4 = request.form['option4']
        correct_option = request.form['correct_option']

        existing_question = Question.query.filter_by(statement=statement,quiz_id=quiz_id).first()

templates/admin_summary.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Summary</title>
    <link rel="icon" href="/static/favicon.ico" type="image/quiz_master-icon">
    <script src="https://kit.fontawesome.com/6179833cb5.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="/static/style/admin_summary.css">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
</head>
<body>
    <div class="position-fixed top-0 start-0 end-0 bg-light bg-opacity-55 rounded-4 py-2 text-center shadow">
        <div class="container">
            <div class="d-flex justify-content-between align-items-center">
                <a href="/admin/dashboard"><img src="/static/logo.png" class="logo"></a>
                <nav class="d-flex">
                    <a href="/admin/dashboard" class="nav-link text-decoration-none me-3">Home</a>
                    <a href="/admin/quizzes" class="nav-link text-decoration-none me-3">Quiz</a>
                    <a href="/admin/summary" class="nav-link active text-decoration-none nav-link">Summary</a>
                </nav>
                <div class="d-flex align-items-center">
                    <form action="/admin/search" method="GET" class="d-flex align-items-center">
                        <input type="text" name="query" placeholder="Search" class="form-control rounded-pill ms-3" required>
                        <button class="btn rounded-circle me-5 " type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
                    </form>
                    <span class="text-dark fw-bold">Welcome Admin</span>
                    <a href="/logout" class="btn btn-danger ms-3 rounded-pill">Logout</a>
                </div>
            </div>
        </div>
    </div>
    <br><br><br><br><br>
    <div class="container">
        <div class="chart-container">
            <canvas id="subjectChart"></canvas>
        </div><br><br><br>
        <div class="chart-container">
            <canvas id="monthChart"></canvas>
        </div>
    </div>

    <script>
        let subjectNames = {{ subject_names | tojson }};
        let subjectQuizCounts = {{ subject_quiz_counts | tojson }};

        const subjectCtx = document.getElementById('subjectChart').getContext('2d');

        new Chart(subjectCtx, {
            type: 'bar',
            data: {
                labels: subjectNames,
                datasets: [
                    {
                        label: 'Quizzes',
                        data: subjectQuizCounts,
                        backgroundColor: 'rgba(54, 162, 235, 0.6)',
                        borderColor: 'rgba(54, 162, 235, 1)',
                        borderWidth: 2
                    }
                ]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                scales: {
                    x: {
                        title: {
                            display: true,
                            text: 'Subjects',
                            font: {
                                weight: 'bold',
                                size: 14
                            }
                        }
                    },
                    y: {
                        beginAtZero: true,
                        stepSize: 1,
                        max: Math.max(...subjectQuizCounts) + 5,
                        min: 0,
                        title: {
                            display: true,
                            text: 'Number of Quizzes',
                            font: {
                                weight: 'bold',
                                size: 14
                            }
                        },
                    }
                }
            }
        });

        let months = {{ months | tojson }};
        let monthQuizCounts = {{ month_quiz_counts | tojson }};

        const monthCtx = document.getElementById('monthChart').getContext('2d');

        new Chart(monthCtx, {
            type: 'line',
            data: {
                labels: months,
                datasets: [{
                    label: 'Quiz Posted',
                    data: monthQuizCounts,
                    fill: false,
                    borderColor: 'rgba(75, 192, 192, 1)',
                    tension: 0.1
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                scales: {
                    x: {
                        title: {
                            display: true,
                            text: 'Months',
                            font: {
                                weight: 'bold',
                                size: 14
                            }
                        }
                    },
                    y: {
                        beginAtZero: true,
                        stepSize: 1,
                        max: 25,
                        min: 0,
                        title: {
                            display: true,
                            text: 'Number of Quizzes',
                            font: {
                                weight: 'bold',
                                size: 14
                            }
                        },
                        ticks: {
                            
                        }
                    }
                }
            }
        });
    </script>

    <footer class="text-center py-3 mt-4 text-muted">
        Made with <i class="fas fa-heart text-danger"></i> by Jatin Nahata
    </footer>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="/static/favicon.ico" type="image/quiz_master-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/style/main.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <title>Login - Quest Mantra</title>
</head>
<body>
    <section class="d-flex justify-content-center align-items-center vh-100 position-relative overflow-hidden">
        <img src="/static/images/bg1.jpg" class="position-absolute top-0 start-0 w-100 h-100 object-fit-cover" alt="Background Image">
        <div class="bg-light bg-opacity-25 rounded-4 p-5 text-center shadow-lg" style="backdrop-filter: blur(15px);">
            <h2 class="fw-bold mb-4 text-light">Log In</h2>
            <form method="POST" action="/login">
                <div class="mb-4">
                    <input type="text" name="username" class="form-control form-control-lg text-dark" placeholder="Username" required>
                </div>
                <div class="mb-4">
                    <input type="password" name="password" class="form-control form-control-lg text-dark" placeholder="Password" required>
                </div>
                <button type="submit" class="btn btn-primary btn-lg w-100">Login</button>
                <div class="text-center mt-3">
                    <p class="mb-0 text-dark">Don't have an account? <a href="/register" class="text-decoration-none text-light fw-bold">Register</a></p>
                </div>
            </form>
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <div class="flash-messages mt-3">
                    {% for category, message in messages %}
                        <div class="flash-message {{ category }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        {% endwith %}
        </div>
    </section>
</body>
</html>

templates/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search</title>
    <link rel="icon" href="/static/favicon.ico" type="image/quiz_master-icon">
    <script src="https://kit.fontawesome.com/6179833cb5.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="/static/style/search.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <div class="position-fixed top-0 start-0 end-0 bg-light bg-opacity-55 rounded-4 py-2 text-center shadow">
        <div class="container">
            <div class="d-flex justify-content-between align-items-center">
                <a href="/admin/dashboard"><img src="/static/logo.png" class="logo"></a>
                <nav class="d-flex">
                    <a href="/admin/dashboard" class="nav-link text-decoration-none me-3">Home</a>
                    <a href="/admin/quizzes" class="nav-link text-decoration-none me-3">Quiz</a>
                    <a href="/admin/summary" class="nav-link text-decoration-none nav-link">Summary</a>
                </nav>
                <div class="d-flex align-items-center">
                    <span class="text-dark fw-bold">Welcome Admin</span>
                    <a href="/logout" class="btn btn-danger ms-3 rounded-pill">Logout</a>
                </div>
            </div>
        </div>
    </div>
    <div class="container pt-5">
        <div class="row">
        {% if not results['Users'] and not results['Subjects'] and not results['Chapters'] %}
            <h3 class="text-center">No Query Found</h3>
            <h2 class="text-muted">Search for "{{ query }}"</h2>
            <p class="text-danger fw-bold">No results found for "{{ query }}"</p>
        {% endif %}
        </div>
    </div>
    <div class="container pt-5">
        <div class="row">
            {% if results['Users'] %}
                <h2 class="text-muted">Search for "{{ query }}" in User</h2>
                <div class="col-md-12 mb-4">
                    <div class="user-box">
                        <div class="text-center">
                            <div class="subject-item">
                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>Username</th>
                                            <th>Full Name</th>
                                            <th>Qualification</th>
                                            <th>Date of Birth</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for user in results['Users'] %}
                                        <tr>
                                            <td>{{ user.username }}</td>
                                            <td>{{ user.full_name }}</td>
                                            <td>{{ user.qualification }}</td>
                                            <td>{{ user.dob }}</td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>    
    <div class="container pt-5">
        <div class="row">
            {% if results['Subjects'] %}
                    <h2 class="text-muted">Search for "{{ query }}" in Subject</h2>
            {% endif %}
            {% if results['Subjects'] %}
                {% for subject in results['Subjects'] %}
                <div class="col-md-12 mb-4">
                    <div class="subject-box">
                        <div class="text-center">
                            <div class="subject-item">
                                <span class="fw-bold me-3">{{ subject.subject_name }}</span>
                                <a href="#" class="text-success me-3" data-bs-toggle="modal" data-bs-target="#editSubjectModal{{ subject.id }}" title="Edit">
                                    <i class="fa-solid fa-pen"></i>
                                </a>
                                <form action="{{ url_for('admin.delete_subject', subject_id=subject.id) }}" method="POST" style="display:inline;">
                                    <a href="#" class="text-danger" onclick="if(confirm('Are you sure you want to delete this subject?')) this.closest('form').submit(); return false;" title="Delete">
                                        <i class="fa-solid fa-trash"></i>
                                    </a>
                                </form>

                                <div class="modal fade" id="editSubjectModal{{ subject.id }}" tabindex="-1" aria-labelledby="editSubjectModal{{ subject.id }}Label">
                                    <div class="modal-dialog modal-dialog-centered">
                                        <div class="modal-content">
                                            <div class="modal-header justify-content-center">
                                                <div class="w-100 text-center">
                                                    <h5 class="modal-title fw-bold" id="editSubjectModal{{ subject.id }}Label">Edit Subject</h5>
                                                </div>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                            </div>
                                            <div class="modal-body">
                                                <form method="POST" action="{{ url_for('admin.edit_subject', subject_id=subject.id) }}" style="display: inline;">
                                                    <div class="mb-3">
                                                        <label for="subject_name" class="form-label">Subject Name:</label>
                                                        <input type="text" id="subject_name" name="subject_name" class="form-control" value="{{ subject.subject_name }}"required>
                                                    </div>
                                                    <div class="mb-3">
                                                        <label for="description" class="form-label">Description:</label>
                                                        <textarea id="description" name="description" class="form-control" rows="3" required>{{ subject.description }}</textarea>
                                                    </div>
                                                    <div class="d-flex justify-content-center text-dark">
                                                        <button type="submit" class="btn btn-warning shadow">Save Changes</button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>Chapter ID</th>
                                            <th>Chapter Name</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for chapter in subject.chapter %}
                                            <tr>
                                                <td>{{ chapter.id }}</td>
                                                <td>{{ chapter.chapter_name }}</td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
    <div class="container pt-5">
        <div class="row">
            {% if results['Chapters'] %}
                    <h2 class="text-muted">Search for "{{ query }}" in Chapter</h2>
            {% endif %}
            {% if results['Chapters'] %}
                {% for chapter in results['Chapters'] %}
                <div class="col-md-12 mb-4">
                    <div class="chapter-box">
                        <div class="text-center">
                            <div class="subject-item">
                                <span class="fw-bold me-3">{{ chapter.chapter_name }}</span>
                                <a href="#" class="text-success me-3" data-bs-toggle="modal" data-bs-target="#editChapterModal{{ chapter.id }}" title="Edit">
                                    <i class="fa-solid fa-pen"></i>
                                </a>
                                <form action="{{ url_for('admin.delete_chapter', chapter_id=chapter.id) }}" method="POST" style="display:inline;">
                                    <a href="#" class="text-danger" onclick="if(confirm('Are you sure you want to delete this chapter?')) this.closest('form').submit(); return false;" title="Delete">
                                        <i class="fa-solid fa-trash"></i>
                                    </a>
                                </form>

                                <div class="modal fade" id="editChapterModal{{ chapter.id }}" tabindex="-1" aria-labelledby="editChapterModalLabel{{ chapter.id }}">
                                    <div class="modal-dialog modal-dialog-centered">
                                        <div class="modal-content">
                                            <div class="modal-header justify-content-center">
                                                <div class="w-100 text-center">
                                                    <h5 class="modal-title fw-bold" id="editChapterModalLabel{{ chapter.id }}">Edit Chapter</h5>
                                                </div>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                            </div>
                                            <div class="modal-body">
                                                <form action="{{ url_for('admin.edit_chapter', chapter_id=chapter.id) }}" method="POST">
                                                    <div class="mb-3">
                                                        <label for="chapter_name_{{ chapter.id }}" class="form-label">Chapter Name</label>
                                                        <input type="text" id="chapter_name_{{ chapter.id }}" name="chapter_name" class="form-control" value="{{ chapter.chapter_name }}" required>
                                                    </div>
                                                    <div class="mb-3">
                                                        <label for="description" class="form-label">Description</label>
                                                        <textarea id="description" name="description" class="form-control" rows="3" required>{{ chapter.description }}</textarea>
                                                    </div>
                                                    <div class="d-flex justify-content-center">
                                                        <button type="submit" class="btn btn-warning">Save Changes</button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <table class="table table-striped mt-3">
                                    <thead>
                                        <tr>
                                            <th>Subject</th>
                                            <th>No. of Quizzes</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>{{ chapter.subject.subject_name }}</td>
                                            <td>{{ chapter.quiz | length }}</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
</body>
</html>